### PR TITLE
Issues 89 (complete) and 97 (partially complete) - Styling and completing Register to Vote flow, adding completedAction function

### LINKED ISSUE #89: Styling/Workflow fixes for Register To Vote
# Goal

- Eligibility check 
- Progress bar
- Challenger register to vote correct routing to the register to vote workflow (US1.3)

### LINKED ISSUE #95: Election reminder action workflow
User Story 6

### PR DESCRIPTION
**Pull request by dvorakjt**
## Overview 
This PR makes a number of changes to the Register to Vote flow. These include:
-Addition of tooltips
-Addition of progress bar
-Eligibility check based on birthday and state
-Integration with new API url, registration status check prior to OtherInfo page
-Loading indication
-Frontend form field validation

Additionally, it adds the completedAction function to the Election Reminders page

## Test Plan 
This PR was tested manually.

## Follow ups 
-Auto-completion of form fields on state websites/redirection to these websites upon form completion

### CODE REVIEW

**Comment by rickyyx** [comment]
Great work Joe! A lot of details that need to be updated, and very impressive that you are getting on top of them. The process bar and the tooltip additions are looking really neat here. 

Pulled the PR and poked around a bit on my own, should I be expecting some different colors for some of the error messages? E.g.: 
image


Will I be able to go through the entire workflow if I am actually not eligible for voting? (I am not a citizen)

**Comment by dvorakjt** [comment]
Here is a video of the working PR:
https://drive.google.com/file/d/1_EfJ00BYTuZrRVyXKZy61jOg4W9HJFMj/view

**Comment by dvorakjt** [comment]
Hi Ricky, I will double check that all error messages display with the same styling attributes applied. As for continuing if you are not a citizen, I believe you are not permitted to continue the process if you are not a citizen (if the checkbox at the beginning is left unchecked, an error message should be displayed and you should not be able to advance. I think I may still need to add this check to the button that appears in the modal--please let me know if this is the correct behavior). Additionally, there is one more detail that I've become aware of that I need to fix -- if you change your birthday after the application determines that you are underage, it doesn't re-evaluate this status and update it if you correct the birthday so as to indicate that you are eligible. Finally, the "nevermind" buttons don't redirect the user anywhere--is this the correct behavior? I will double-check the figma but I'd appreciate your input on this matter as well. I will make this updates and update the PR, hopefully within the next day or two

**Comment by rickyyx** [comment]
>  I think I may still need to add this check to the button that appears in the modal--please let me know if this is the correct behavior

Yeah, I think this makes sense for the eventual logic. I was wondering if I could test the flow on my own, e.g. the ID information could be fake right? So I could pretend to be a citizen and have the form prefilled but it will not be a valid registration when I mailed in since the info I provided is not correct. 


> Finally, the "nevermind" buttons don't redirect the user anywhere--is this the correct behavior? 

I think it wasn't specified on the figma, and I think we could treat it as a no-op, just close the popup I guess.

**Comment by dvorakjt** [comment]
I fixed the conflicts and added the LoadingWheel to ElectionReminders. A LoadingWheel with `overlay` set to `false` will show a white background.

**Pull request merged**
