### PR TITLE
Issue #155 - Add Address Validation to Voter Reg Address Form

### PR DESCRIPTION
**Pull request by dvorakjt**
## Overview 
This PR adds address real-time validation to the AddressBlock component through calls to the /validateAddress endpoint of the API. Additionally, it modifies the names of some fields within the voter registration data object to conform to new fields in the API's various endpoints. Finally, a few console.logs were commented out/removed.

## Test Plan 
This PR was tested via end-to-end testing in the browser. Screencast: https://watch.screencastify.com/v/jrtBvRlC9Vo77gtTwYXU

## Follow ups 
The styling of the address validation message may need to be updated according according to the design team's vision.

### CODE REVIEW

**Comment by dvorakjt** [comment]
I'm not sure why the PR is saying that it includes 34 commits...

**Review by Devanshusp — APPROVED** [review]
Thanks @dvorakjt, tested this and it works great! Hopefully this will squash any address errors people can have in the future 🤞

Btw, I think it shows 34 commits since this shows your previous commits that you have worked on (even before making this pr).
You can avoid this by making a new personal branch for each feature; make changes there and push from there - I believe this will fix the extra commits.

**Review by Devanshusp — CHANGES_REQUESTED** [review]
Whoops @dvorakjt, just noticed there's a merge conflict - once that's updated, I'll merge this ☺️

**Comment by dvorakjt** [comment]
Hi @Devanshusp, the merge conflict should be fixed now, I believe. Let me know if it's not/if there are any other issues. Thanks!

**Review by Devanshusp — APPROVED** [review]
Thanks @dvorakjt! This looks great!

**Pull request merged**
