### PR TITLE
Tech-Design UX Walkthrough Item 9 partial

### PR DESCRIPTION
**Pull request by wcouturiaux**
https://user-images.githubusercontent.com/37006112/175458533-cc59efc1-c56c-4984-9ed8-35af61f709e2.mov

https://user-images.githubusercontent.com/37006112/176585887-7f6ce0ad-6a4c-4e33-8294-8fd086c4e553.mov

### CODE REVIEW

**Comment by rickyyx** [comment]
Hey Will, thanks for working on this, could you add a few screenshots/screencast even better to the PR? This way we could also link it to the table for designers to review.

**Comment by wcouturiaux** [comment]
@rickyyx added a screen recording. One thing I noticed sometimes it shows NaN and sometimes it shows 8 days after signup. I'm not sure but thinking this might be related to timing of creating a user in firebase?

**Comment by rickyyx** [comment]
Looking good to me!! 
<div><br/>via <a href="https://giphy.com/agt/">America&#x27;s Got Talent</a> on <a href="https://giphy.com/gifs/americasgottalent-agt-americas-got-talent-26BRBKqUiq586bRVm">GIPHY</a></div>

**Review by rickyyx — APPROVED** [review]

**Comment by wcouturiaux** [comment]
Apologies for the craziness with force pushes. I thought this was already merged and that led to what it did. The only change from what @rickyyx approved previously is items 3 and 4 in the overview.

**Comment by wcouturiaux** [comment]
@rickyyx or @Devanshusp can you please review the changes since last approval?

**Review by Devanshusp — APPROVED** [review]
Hey @wcouturiaux, thanks for working on this! Everything looks good to me- I really appreciate your attention to fixing some of the styling issues and refactoring the code to help remove bootstrap!

**Pull request merged**
